# Generated by Django 5.0.4 on 2024-06-10 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, message='Цена не бможет быть меньше 1')], verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
